version: '3.9'
services:
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  backend:
    image: blog-backend
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - mongo
volumes:
  mongo-data:
