version: '3.9'
services:
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  backend:
    image: blog-backend-dev
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo
  frontend:
    image: blog-frontend-dev
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:4000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host --port 5173
    depends_on:
      - backend
volumes:
  mongo-data:
