version: '3.9'
services:
  mongo:
    container_name: blog-mongo-dev
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  backend:
    container_name: blog-backend-dev
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
  frontend:
    container_name: blog-frontend-dev
    build:
      context: frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:4000/api
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host --port 5173"
    depends_on:
      - backend
volumes:
  mongo-data:
